// Generates the dark color scheme from the light stylesheets.
//
//   light rule  .card { background: #fffefa; color: #263d32 }
//        |      same selector, same media wrapper, same source order
//        v
//   dark rule   .card { background: <dark paper>; color: <light ink> }
//
// Each color keeps its hue and has its perceptual (OKLCH) lightness flipped, so paper
// becomes a deep surface and ink becomes light text. Every color-related declaration is
// mirrored, including ones without a color (border: 0), so the dark cascade resolves exactly
// like the light one. The block is written between markers at the end of each file, twice:
//
//   system dark, no choice saved   :root:not([data-theme="light"]) .card { ... }
//   student chose dark             :root[data-theme="dark"] .card { ... }
//
// Both scopes add the same specificity to every rule, so relative order is unchanged and each
// dark rule still outranks its own light rule. Print stays light.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const THEMED_FILES = ['src/styles.css', 'src/guide.css', 'src/high-school.css'];
const START = '/* dark-theme:start (generated by scripts/dark-theme.js; do not edit by hand) */';
const END = '/* dark-theme:end */';
const COLOR = /#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})\b|rgba?\([^)]*\)|\b(?:white|black)\b/g;
const COLOR_PROPS = /^(?:color|background(?:-color|-image)?|border(?:-(?:top|right|bottom|left))?(?:-color)?|outline(?:-color)?|box-shadow|text-shadow|fill|stroke|accent-color|caret-color|text-decoration(?:-color)?|color-scheme)$/;

// sRGB <-> OKLab (Björn Ottosson's reference matrices).
const toLinear = c => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const toGamma = c => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);
function rgbToOklab([r, g, b]) {
  [r, g, b] = [r, g, b].map(v => toLinear(v / 255));
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return [0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s];
}
function oklabToRgb([L, a, b]) {
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s].map(toGamma);
}
const inGamut = rgb => rgb.every(v => v >= -1e-4 && v <= 1 + 1e-4);

function parseColor(text) {
  if (text === 'white') return [255, 255, 255, 1];
  if (text === 'black') return [0, 0, 0, 1];
  if (text.startsWith('#')) {
    let hex = text.slice(1);
    if (hex.length <= 4) hex = [...hex].map(ch => ch + ch).join('');
    const n = [0, 2, 4, 6].map(i => parseInt(hex.slice(i, i + 2) || 'ff', 16));
    return [n[0], n[1], n[2], n[3] / 255];
  }
  const parts = text.slice(text.indexOf('(') + 1, -1).split(/[\s,/]+/).filter(Boolean).map(Number);
  return [parts[0], parts[1], parts[2], parts.length > 3 ? parts[3] : 1];
}
const hex2 = v => Math.round(Math.min(255, Math.max(0, v))).toString(16).padStart(2, '0');
function formatColor([r, g, b, alpha]) {
  if (alpha >= 1) return `#${hex2(r)}${hex2(g)}${hex2(b)}`;
  return `rgba(${Math.round(r)}, ${Math.round(g)}, ${Math.round(b)}, ${Math.round(alpha * 1000) / 1000})`;
}

/** Flip perceptual lightness, keep hue, and pull chroma back into sRGB. */
export function darkColor(text, prop = 'color') {
  const [r, g, b, alpha] = parseColor(text);
  if (/shadow/.test(prop)) return formatColor([0, 0, 0, Math.min(0.6, alpha * 3 + 0.12)]);
  const [L, a, bb] = rgbToOklab([r, g, b]);
  const C = Math.hypot(a, bb);
  const h = Math.atan2(bb, a);
  // Text is lifted a little more than surfaces so secondary text keeps its contrast margin.
  const isText = /^(?:color|fill|stroke|caret-color|text-decoration(?:-color)?)$/.test(prop);
  const nextL = 0.16 + (isText ? 0.82 * (1 - L) ** 0.68 : 0.8 * (1 - L) ** 0.82);
  let nextC = C * 0.9;
  let rgb = oklabToRgb([nextL, nextC * Math.cos(h), nextC * Math.sin(h)]);
  while (!inGamut(rgb) && nextC > 0.001) {
    nextC *= 0.92;
    rgb = oklabToRgb([nextL, nextC * Math.cos(h), nextC * Math.sin(h)]);
  }
  return formatColor([...rgb.map(v => v * 255), alpha]);
}

// Minimal CSS reader for these hand-written files: rules, nested at-rules, comments, strings.
function parse(css) {
  let i = 0;
  const skipComment = () => { const end = css.indexOf('*/', i + 2); i = end < 0 ? css.length : end + 2; };
  function readUntil(stops) {
    let out = '';
    let depth = 0;
    while (i < css.length) {
      const ch = css[i];
      if (ch === '/' && css[i + 1] === '*') { skipComment(); continue; }
      if (ch === '"' || ch === "'") {
        const start = i++;
        while (i < css.length && css[i] !== ch) i += css[i] === '\\' ? 2 : 1;
        out += css.slice(start, ++i);
        continue;
      }
      if (ch === '(') depth++;
      if (ch === ')') depth--;
      if (depth === 0 && stops.includes(ch)) return out;
      out += ch;
      i++;
    }
    return out;
  }
  function block() {
    const nodes = [];
    while (i < css.length) {
      const prelude = readUntil(['{', '}']).trim();
      if (i >= css.length || css[i] === '}') { i++; return nodes; }
      i++; // {
      if (prelude.startsWith('@media') || prelude.startsWith('@supports')) {
        nodes.push({ type: 'at', prelude, children: block() });
      } else if (prelude.startsWith('@')) {
        nodes.push({ type: 'skip', body: block() });
      } else {
        const decls = [];
        while (i < css.length && css[i] !== '}') {
          const decl = readUntil([';', '}']).trim();
          if (css[i] === ';') i++;
          const at = decl.indexOf(':');
          if (at > 0) decls.push([decl.slice(0, at).trim(), decl.slice(at + 1).trim()]);
        }
        i++; // }
        nodes.push({ type: 'rule', selector: prelude.replace(/\s+/g, ' '), decls });
      }
    }
    return nodes;
  }
  return block();
}

// Overlays dim what is behind them, so they stay dark instead of flipping to a light veil.
function themeDecl([prop, value], overlay = false) {
  const lower = prop.toLowerCase();
  const custom = lower.startsWith('--');
  if (custom ? !value.match(COLOR) : !COLOR_PROPS.test(lower)) return null;
  if (lower === 'color-scheme') return `${prop}: ${value.replace(/\blight\b/, 'dark')}`;
  const mode = overlay && lower.startsWith('background') ? 'shadow' : lower;
  return `${prop}: ${value.replace(COLOR, match => darkColor(match, mode))}`;
}

const SCOPES = { system: ':not([data-theme="light"])', chosen: '[data-theme="dark"]' };

/** Prefix each selector in a list with the root scope, merging into :root or html when present. */
export function scopeSelector(selector, scope) {
  const parts = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i <= selector.length; i++) {
    const ch = selector[i];
    if (ch === '(') depth++;
    if (ch === ')') depth--;
    if ((ch === ',' && depth === 0) || i === selector.length) { parts.push(selector.slice(start, i).trim()); start = i + 1; }
  }
  return parts.map(part => {
    const root = part.match(/^(:root|html)(?![\w-])/);
    return root ? `${root[1]}${scope}${part.slice(root[1].length)}` : `:root${scope} ${part}`;
  }).join(',');
}

function themeNodes(nodes, scope) {
  const out = [];
  for (const node of nodes) {
    if (node.type === 'rule') {
      const overlay = node.selector.includes('::backdrop');
      const decls = node.decls.map(decl => themeDecl(decl, overlay)).filter(Boolean);
      if (decls.length) out.push(`${scopeSelector(node.selector, scope)}{${decls.join(';')}}`);
    } else if (node.type === 'at' && !/\bprint\b/.test(node.prelude)) {
      const inner = themeNodes(node.children, scope);
      if (inner.length) out.push(`${node.prelude}{${inner.join('')}}`);
    }
  }
  return out;
}

export function stripDarkBlock(css) {
  const start = css.indexOf(START);
  return start < 0 ? css : css.slice(0, start).replace(/\s+$/, '\n');
}

export function withDarkBlock(css) {
  const light = stripDarkBlock(css);
  const nodes = parse(light);
  const system = themeNodes(nodes, SCOPES.system).join('\n');
  const chosen = themeNodes(nodes, SCOPES.chosen).join('\n');
  return `${light}\n${START}\n@media screen and (prefers-color-scheme: dark){\n${system}\n}\n@media screen{\n${chosen}\n}\n${END}\n`;
}

const root = fileURLToPath(new URL('..', import.meta.url));
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const file of THEMED_FILES) {
    const target = path.join(root, file);
    const current = await readFile(target, 'utf8');
    const next = withDarkBlock(current);
    if (next === current) continue;
    stale++;
    if (check) console.error(`${file}: dark theme is out of date. Run npm run theme:dark.`);
    else await writeFile(target, next);
  }
  if (check && stale) process.exit(1);
  console.log(check ? 'Dark theme is up to date.' : `Dark theme written for ${THEMED_FILES.length} stylesheets.`);
}
